
-- CREATE USER
CREATE TABLE NTD_CALCULATOR.`USER` (
	USER_ID BIGINT auto_increment NOT NULL,
	USERNAME VARCHAR(200) NOT NULL,
	PASSWORD varchar(200) NOT NULL,
	STATUS BIT NOT NULL,
	CONSTRAINT USER_PK PRIMARY KEY (USER_ID),
	CONSTRAINT USER_UNIQUE_USERNAME UNIQUE KEY (USERNAME)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

-- CREATE OPERATION
CREATE TABLE NTD_CALCULATOR.OPERATION (
	OPERATION_ID BIGINT auto_increment NOT NULL,
	`TYPE` INT NOT NULL,
	COST DOUBLE NOT NULL,
	CONSTRAINT OPERATION_PK PRIMARY KEY (OPERATION_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

-- INSERT OPERATIONS
INSERT INTO NTD_CALCULATOR.OPERATION (OPERATION_ID,`TYPE`,COST) VALUES
	 (1,1,0.5),
	 (2,2,0.5),
	 (3,3,1.0),
	 (4,4,1.0),
	 (5,5,1.5),
	 (6,6,1.0),
	 (7,7,0.0);


-- CREATE RECORD
CREATE TABLE NTD_CALCULATOR.RECORD (
	RECORD_ID BIGINT auto_increment NOT NULL,
	OPERATION_ID BIGINT NOT NULL,
	USER_ID BIGINT NOT NULL,
	AMOUNT DOUBLE NOT NULL,
	USER_BALANCE DOUBLE NULL,
	OPERATION_RESPONSE varchar(100) NOT NULL,
	CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
	DELETION_DATE DATETIME NULL,
	CONSTRAINT RECORD_PK PRIMARY KEY (RECORD_ID),
	CONSTRAINT RECORD_USER_FK FOREIGN KEY (USER_ID) REFERENCES NTD_CALCULATOR.`USER`(USER_ID),
	CONSTRAINT RECORD_OPERATION_FK FOREIGN KEY (OPERATION_ID) REFERENCES NTD_CALCULATOR.OPERATION(OPERATION_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;