services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=NTD_CALCULATOR
      - MYSQL_ROOT_PASSWORD=2ASdxakA&&mrMn
    ports:
      - '3306:3306'
    volumes:
      - ./CREATE_AND_POPULATE_NTD_CALCULATOR.sql:/docker-entrypoint-initdb.d/1.sql:ro
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
  backend:
    build: &build-definition
      context: .
      dockerfile: ./local.Dockerfile
    container_name: ntd_calculator_backend
    depends_on: 
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - '8080:8080'